apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: venves-uk-tls
spec:
  secretName: venves-uk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: venves.uk
  dnsNames:
    - venves.uk
    - k8s.venves.uk
