apiVersion: v1
kind: Service
metadata:
  name: nginx-web3
  labels:
    app: nginx-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32083
  selector:
    app: nginx-app
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-web3-volume
  labels:
    app: nginx-app
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nginx2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-web3-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web3
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-app
  replicas: 2
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nginx-app
    spec:
      volumes:
        - name: nginx-web3-storage
          persistentVolumeClaim:
            claimName: nginx-web3-claim
      containers:
        - name: nginx-web3
          image: ubuntu/nginx
          ports:
            - containerPort: 80
              name: nginx-web3
          volumeMounts:
            - mountPath: "/var/www/html"
              name: nginx-web3-storage