version: '3.3'
# OK
services:
  # Database
  db:
    image: mysql:5.7
    container_name: d_db_server
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: C0rr3ct!0n123
      MYSQL_DATABASE: wpsite
      MYSQL_USER: svc-admin
      MYSQL_PASSWORD: C0rr3ct!0n123

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: d_phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: C0rr3ct!0n123

  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: d_wp-web
    ports:
      - '8080:80'
      - '8443:443'
    restart: always
    volumes:
      - ./wp_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: svc-admin
      WORDPRESS_DB_PASSWORD: C0rr3ct!0n123
      WORDPRESS_DB_NAME: wpsite
