version: '3'
# OK
# WP + MySQL + phpmyadmin
services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: C0rr3ct!0n123
      MYSQL_DATABASE: wpsite
      MYSQL_USER: svc-admin
      MYSQL_PASSWORD: C0rr3ct!0n123
#    networks:
#      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: C0rr3ct!0n123 
#    networks:
#      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./wpsite1:/var/www/html']
    #  - ./src:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: svc-admin
      WORDPRESS_DB_PASSWORD: C0rr3ct!0n123
      WORDPRESS_DB_NAME: wpsite
      WORDPRESS_TABLE_PREFIX: wp_
#    networks:
#      - wpsite
#networks:
#  wpsite:
volumes:
  db_data: