version: '3.3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: C0rr3ct!0n123
      MYSQL_DATABASE: wpsite
      MYSQL_USER: svc-admin
      MYSQL_PASSWORD: C0rr3ct!0n123

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '3081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: C0rr3ct!0n123

  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '3080:80'
    restart: always
    volumes:
      - wordpress_files:/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: svc-admin
      WORDPRESS_DB_PASSWORD: C0rr3ct!0n123
      WORDPRESS_DB_NAME: wpsite

volumes:
  db_data:
    driver: local
  wordpress_files:
    driver: local