version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: svc-user
      WORDPRESS_DB_PASSWORD: 'Pa55w0rd'
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: svc-admin
      MYSQL_PASSWORD: 'Pa55w0rd'
      MYSQL_RANDOM_ROOT_PASSWORD: 'Pa55w0rd'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: