apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-mysql-pvolume
  labels: 
    storage-tier: mysql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.0
  nfs: 
    path: /kube/mysql
    server: 192.168.15.252 
    readOnly: false